module.exports = {
  ERROR_UNKNOWN: -1,
  ERROR_DATABASE: 1,
  ERROR_INVALID_CONTENT_TYPE: 2,
  ERROR_INVALID_BODY_FORMAT: 3,
  ERROR_MISSING_PARAMETER: 4,
  ERROR_INVALID_PARAMETER_TYPE: 5,
  ERROR_PASSWORD_INVALID: 6
};

